[package]
name = "liftm/patch-json"
version = "0.1.0"
description = "Tool for generating and applying RFC 6902 JSON patches"
license = "Apache-2.0"
repository = "https://github.com/jcaesar/patch-json"
readme = "README.md"

[[module]]
name = "patch-json"
source = "target/wasm32-wasi/release/patch-json.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "patch-json"
module = "patch-json"
